import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import logoImage from 'logotipo.png';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className="headers">
          <img src="/logotipo.png" alt="Logo del Banco" />
          <h1>Banco Argentino Sin Inflación</h1>
        </div>
      </body>
    </html>
  )
}
